### ISSUE TITLE
del + supplied

### ISSUE THREAD

**Issue by GusRiva** [Romische-Inschriften-Augsburg-RIA/database#3]
Ich habe folgendes gesehen:

```
<del rend="erasure">
                <supplied reason="lost">
                      .....
                </supplied>
</del>
```

Erlaubt in der TEI, aber inwiefern ist das anders als nur `<del>`? Wie soll es dann im Lesetext aussehen?

Nach Leiden+ mache ich `<del>` so: [[ Text ]] 

und `<supplied>` so: [ Text ] 

Soll es am Ende so sein?: [[ [ Text ] ]]

**Comment by chalkenteros** [comment]
Das ist nach https://epidoc.stoa.org/gl/latest/trans-erasedillegible.html korrekt so. Man muss bei Rasuren folgende Fälle unterscheiden: (1) Gelöscht, aber noch lesbar >> [[Text]]; (2) Gelöscht, nicht mehr lesbar, aber ergänzt >> [[[Text]]]; (3) Gelöscht und nicht mehr lesbar >> [[.]].

Typographisch korrekt müsste man für die Rasur eigentlich Doppelklammern und nicht zwei Einfachklammern verwenden, dann wäre es auch leichter lesbar. S. die Beispiele in der oben verlinkten EpiDoc-Dokumention.

**Comment by chalkenteros** [comment]
Nachtrag: Bei der EpiDoc-Konversion der EDH wurde das vielfach/immer(?) nicht korrekt umgesetzt. Daher stehen bei Rasuren an vielen Stellen noch [] im Text, die nicht in Tags umgesetzt wurden. Das haben wir auf dem Schirm.

**Comment by GusRiva** [comment]
Ok, prima, das macht Sinn! Dann würde es so in der Transformation einsetzen.
