### ISSUE TITLE
Problem with <abbr>

### ISSUE THREAD

**Issue by chalkenteros** [Romische-Inschriften-Augsburg-RIA/database#5]
Bsp: HD053611

```
<expan><abbr>P</abbr><ex>ublius</ex></expan> <abbr>P</abbr> Helius</persName>
```

müsste nach https://epidoc.stoa.org/gl/latest/trans-abbrevnotex.html angezeigt werden als: P(ublius) P(---) Helius

wird aber angezeigt als: P(ublius) P

Es wird also zum einen die "leere" Auflösung der Abkürzung nicht angezeigt, zum anderen der restliche Text in der Zeile unterdrückt.

**Comment by GusRiva** [comment]
Sollte jetzt gelöst sein
